import type { Preview } from '@storybook/react-vite';
import { useEffect } from 'react';
import '../tailwind.css';

const preview: Preview = {
  globalTypes: {
    tailwindEnabled: {
      description: 'Toggle Tailwind CSS',
      defaultValue: true,
      toolbar: {
        title: 'Tailwind',
        icon: 'lightning',
        items: [
          { value: true, title: 'Enabled' },
          { value: false, title: 'Disabled' },
        ],
      },
    },
  },
  decorators: [
    (Story, context) => {
      const { tailwindEnabled } = context.globals;

      useEffect(() => {
        // Find the Tailwind stylesheet generated by Vite
        const styleTags = Array.from(document.querySelectorAll('style'));
        const tailwindStyle = styleTags.find(style =>
          style.getAttribute('data-vite-dev-id')?.includes('tailwind.css')
        );

        if (tailwindStyle) {
          // Toggle the disabled attribute
          tailwindStyle.disabled = !tailwindEnabled;
        }
      }, [tailwindEnabled]);

      return <Story />;
    },
  ],
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },

    a11y: {
      test: 'todo'
    },
  },
};

export default preview;